
server:
  host: "0.0.0.0"
  port: 8080
  debug: true

database:
  url: "sqlite:///app.db"

middleware:
  cors:
    enabled: true
    origins: ["*"]
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
