version = 1

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = [
    "react",
    "vue",
    "ember",
    "angularjs",
    "meteor",
    "angular"
]
environment = [
    "nodejs",
    "jquery",
    "mongo",
    "browser",
    "jest",
    "cypress",
    "vitest",
    "mocha",
    "jasmine"
]

[[analyzers]]
name = "shell"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"