
name: "AI Bot"
environment: "development"
debug: true
host: "0.0.0.0"
port: 8080
cors_origins:
  - "http://localhost:3002"
  - "http://localhost:3003"
  - "https://ai-bot-template-1.jonathanprocter.repl.co"
