app:
  name: 'NCLEX Study System'
  env: ${FLASK_ENV:-development}
  debug: ${FLASK_DEBUG:-false}
  host: '0.0.0.0'
  port: 8080

database:
  url: ${DATABASE_URL:-sqlite:///app.db}
  pool_size: 20
  max_overflow: 10

monitoring:
  log_level: ${LOG_LEVEL:-INFO}
  metrics_interval: 30
  health_check_interval: 60

middleware:
  cors_enabled: true
  cache_enabled: true
  request_timeout: 30

analytics:
  enabled: true
  tracking_interval: 5000
  retention_days: 30
