
flask:
  ENV: production
  DEBUG: false
  TESTING: false
  SECRET_KEY: ${SECRET_KEY}

database:
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@0.0.0.0:5432/app_db
  SQLALCHEMY_POOL_SIZE: 10
  SQLALCHEMY_POOL_TIMEOUT: 30

server:
  host: 0.0.0.0
  port: 81
  workers: 4

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
